### ISSUE TITLE
hash_to_arch.pickle is missing

### ISSUE THREAD

**Issue by KelvinYang0320** [SamsungLabs/blox#3]
@vaenyr  Should I get `data/hash_to_arch.pickle` after running `./train_multi_gpu.sh <next_model_to_train> <models_per_gpu>`?
I add a python script to create `data/hash_to_arch.pickle` for now:
```python
import blox
import pickle


with open('data/unique_archs.pickle', 'rb') as f:
    models = pickle.load(f)
hash_to_arch = {}
for arch_vec in models:
    h = blox.search_space.get_model_hash(arch_vec)
    hash_to_arch[h] = arch_vec
with open("./data/hash_to_arch.pickle", 'wb') as f:
    pickle.dump(hash_to_arch, f)

```

**Comment by vaenyr** [comment]
Hi, you're script is a correct way of getting the hash to arch pickle - if it's not created by default, could you maybe add a relevant patch to the make_dataset.py? Basically if the file does not exist, create it like that.

Sorry for the trouble, seems like I removed more than I wanted when cleaning up the code - thank you for checking everything!

**Comment by KelvinYang0320** [comment]
Closed as completed due to https://github.com/SamsungLabs/blox/pull/4
